name: Build App

on:
  push:
    tags:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
          - os: ubuntu-latest
            arch: arm64
          - os: windows-latest
            arch: x64
          - os: macos-latest
            arch: x64
          - os: macos-latest
            arch: arm64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Set version
        run: npm version $GITHUB_REF_NAME --no-git-tag-version

      - name: Install Dependencies
        run: npm install

      - name: Build App
        run: npx electron-builder --publish never --${{ matrix.arch }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts-${{ runner.os }}-${{ matrix.arch }}
          path: |
            release-builds/*.msi
            release-builds/*.zip
            release-builds/*.deb
            release-builds/*.rpm
            release-builds/*.dmg
