name: Build and Release App

on:
  push:
    tags:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Set version
        run: npm version ${{ github.ref_name }} --no-git-tag-version

      - name: Install Dependencies
        run: npm install

      - name: Build Frontend
        run: npx vue-cli-service build

      - name: Package App
        run: npx electron-builder --publish never

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts-${{ runner.os }}
          path: |
            release-builds/*.msi
            release-builds/*.zip
            release-builds/*.deb
            release-builds/*.rpm
            release-builds/*.dmg

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Stream Monitor ${{ github.ref_name }}
          draft: true
          files: |
            artifacts/**/*.msi
            artifacts/**/*.zip
            artifacts/**/*.deb
            artifacts/**/*.rpm
            artifacts/**/*.dmg
